### ISSUE TITLE
为啥点击了 `话题PK-加入羊群 ` 之后没有反映， 并且进入游戏的时候画面会倒置

### ISSUE THREAD

**Issue by Jingjiasheng** [george-jiang-wow/yanglegeyang#1]

**Comment by Jingjiasheng** [comment]
详情可以进入 https://ylgy.automan.vip 查看

**Comment by Jingjiasheng** [comment]
![image](https://user-images.githubusercontent.com/65474840/190300387-b4854566-2b92-4fcd-9f81-2e172c6f12bc.png)
报错如上

**Comment by ajavaer** [comment]
err_code: 10003, err_msg: "没有权限", data: null}
data
: 
null
err_code
: 
10003
err_msg
: 
"没有权限"

**Comment by wc222** [comment]
> 详情可以进入 https://ylgy.automan.vip 查看

我点击这个网页进入了游戏，能玩。

**Comment by paulloo** [comment]
部属个静态资源还不简单？  https://t.ddp.life/   : )

**Comment by george-jiang-wow** [comment]
不是我的锅...我只是存了一份代码...还没绕API鉴权...突然就火了...
