### ISSUE TITLE
游戏时不小心点了左边的过关按钮，要等几小时才能重置

### ISSUE THREAD

**Issue by sysdeafult** [george-jiang-wow/yanglegeyang#11]
游戏时不小心点了左边的过关按钮，要等几小时才能重置，清除浏览器缓存不管用
![image](https://user-images.githubusercontent.com/72608492/190627465-6d8eb050-0a1d-40e2-8af3-dffa273d4992.png)

**Comment by simuhunluo** [comment]
清除localstorage就行
![image](https://user-images.githubusercontent.com/22125687/190914327-76fa70f0-e928-4edc-863e-311cee1f1df8.png)

**Comment by fxxph** [comment]
把数据清除掉就好了

**Comment by george-jiang-wow** [comment]
不是我的锅...我只是存了一份代码...还没绕API鉴权...突然就火了...
