### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by kangleyunju** [george-jiang-wow/yanglegeyang#13]
报错index.html:1 Access to XMLHttpRequest at 'file:///C:/Users/Administrator/Downloads/yanglegeyang-main/assets/internal/config.e6604.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

**Comment by george-jiang-wow** [comment]
不是我的锅...我只是存了一份代码...还没绕API鉴权...突然就火了...

**Comment by sxz1314** [comment]
> 不是我的锅...我只是存了一份代码...还没绕API鉴权...突然就火了...

赶紧绕啊

**Comment by george-jiang-wow** [comment]
> > 不是我的锅...我只是存了一份代码...还没绕API鉴权...突然就火了...
> 
> 赶紧绕啊

@sxz1314 自己搭建后端好了。这样比较方便
