### ISSUE TITLE
玩不了

### ISSUE THREAD

**Issue by yangzhi-1** [george-jiang-wow/yanglegeyang#4]
玩不了

**Comment by SleepyAsh0191** [comment]
请自行搭建后端，只需要满足能获取到地图数据就行
![image](https://user-images.githubusercontent.com/64446140/190325808-756e10c3-7965-4376-bca4-f06f1b4c8989.png)

**Comment by MrJdy** [comment]
> 请自行搭建后端，然后自己写，只需要满足能获取到地图数据就行 ![image](https://user-images.githubusercontent.com/64446140/190325808-756e10c3-7965-4376-bca4-f06f1b4c8989.png)

我看都是压缩了的JS，有源码逻辑吗

**Comment by SleepyAsh0191** [comment]
> > 请自行搭建后端，然后自己写，只需要满足能获取到地图数据就行 ![image](https://user-images.githubusercontent.com/64446140/190325808-756e10c3-7965-4376-bca4-f06f1b4c8989.png)
> 
> 我看都是压缩了的JS，有源码逻辑吗

今天晚些我会把我自己修改的版本上传到github上

**Comment by SleepyAsh0191** [comment]
> 

看我自己的后端repo，只不过是硬编码

**Comment by SleepyAsh0191** [comment]
> 请问要构建怎样的数据

看我的后端repo，只不过是硬编码

**Comment by ajavaer** [comment]
> 

大佬请问后端代码在intellj怎么启动，主文件是什么，好像没有数据库文件

**Comment by george-jiang-wow** [comment]
不是我的锅...我只是存了一份代码...还没绕API鉴权...突然就火了...
