### ISSUE TITLE
有没有纯享版

### ISSUE THREAD

**Issue by JulienZeng** [george-jiang-wow/yanglegeyang#7]
就是只有第一第二关那个页面，不要加入羊群啊，pk啊那些乱七八糟的东西
我试过去改源代码，但是打开一看无从下手，看得头疼，看不懂

**Comment by george-jiang-wow** [comment]
不是我的锅...我只是存了一份代码...还没绕API鉴权...突然就火了...

**Comment by george-jiang-wow** [comment]
源代码肯定有混淆的啊
